[package]
name = "harvester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
tokio = { version = "1.10.0", features = ["full"] }
futures = "0.3.16"
url = "2.2.2"
reqwest = "0.11.4"
serde_json = "1.0.66"
serde = { version = "1.0.128", features = ["derive"] }
async-trait = "0.1.51"
flume = "0.10.8"
regex = "1.5.4"
flate2 = "1.0.24"
