name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Update local toolchain
      run: |
        rustup update
        rustup install nightly
        rustup default nightly
        rustup component add clippy rustfmt

    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version

    - name: Lint
      run: |
        cargo fmt -- --check
        cargo clippy -- -D warnings

    - name: Test
      run: |
        cargo check
        cargo test --all

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/bob3000/harvester:latest
          ghcr.io/bob3000/harvester:${{github.ref_name}}
          cache-from: type=registry,ref=bob3000/harvester:latest
          cache-to: type=inline
