name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Update local toolchain
      run: |
        rustup update
        rustup install nightly
        rustup default nightly
        rustup component add clippy rustfmt

    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version

    - name: Lint
      run: |
        cargo fmt -- --check
        cargo clippy -- -D warnings

    - name: Test
      run: |
        cargo check
        cargo test --all

    - name: Build
      run: |
        cargo build --release
